export type FormEntry = {
  id: string;
  date_of_birth: string;
  first_name: string;
  last_name: string;
  school: string;
  phone_number: string;
  home_phone: string;
  parent_phone: string;
  field: string;
  grade: string;
  created: string;
  plan?: number;
  advisor: string | null;
  advisor_id: string | null;
  advisor_name: string | null;
  supervisor: string | null;
  supervisor_id: string | null;
  supervisor_name: string | null;
};
